name: 'FrequentTask'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Run my job
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
          GIT_HOST_1: ${{ secrets.GIT_HOST_1 }}
          GIT_HOST_2: ${{ secrets.GIT_HOST_2 }}
          GIT_HOST_3: ${{ secrets.GIT_HOST_3 }}
          USER: ${{ secrets.USER }}
          EMAIL: ${{ secrets.EMAIL }}
          JOB_REPO: ${{ secrets.JOB_REPO }}
          TZ: Asia/Shanghai
        run: |
          # set ssh
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
          ssh-keyscan "$GIT_HOST_2" >> ~/.ssh/known_hosts
          ssh-keyscan "$GIT_HOST_3" >> ~/.ssh/known_hosts

          # set git information
          git config --global user.name "$USER"
          git config --global user.email "$EMAIL"

          git clone $JOB_REPO
          bash -e jobs/frequent-task.sh
